// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cavalry/transport/discovery.proto

package transport

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DiscoverableServiceTransport struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoverableServiceTransport) Reset()         { *m = DiscoverableServiceTransport{} }
func (m *DiscoverableServiceTransport) String() string { return proto.CompactTextString(m) }
func (*DiscoverableServiceTransport) ProtoMessage()    {}
func (*DiscoverableServiceTransport) Descriptor() ([]byte, []int) {
	return fileDescriptor_discovery_355ed599282d0a1b, []int{0}
}
func (m *DiscoverableServiceTransport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverableServiceTransport.Unmarshal(m, b)
}
func (m *DiscoverableServiceTransport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverableServiceTransport.Marshal(b, m, deterministic)
}
func (dst *DiscoverableServiceTransport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverableServiceTransport.Merge(dst, src)
}
func (m *DiscoverableServiceTransport) XXX_Size() int {
	return xxx_messageInfo_DiscoverableServiceTransport.Size(m)
}
func (m *DiscoverableServiceTransport) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverableServiceTransport.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverableServiceTransport proto.InternalMessageInfo

func (m *DiscoverableServiceTransport) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*DiscoverableServiceTransport)(nil), "Transport.DiscoverableServiceTransport")
}

func init() {
	proto.RegisterFile("cavalry/transport/discovery.proto", fileDescriptor_discovery_355ed599282d0a1b)
}

var fileDescriptor_discovery_355ed599282d0a1b = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4c, 0x4e, 0x2c, 0x4b,
	0xcc, 0x29, 0xaa, 0xd4, 0x2f, 0x29, 0x4a, 0xcc, 0x2b, 0x2e, 0xc8, 0x2f, 0x2a, 0xd1, 0x4f, 0xc9,
	0x2c, 0x4e, 0xce, 0x2f, 0x4b, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x0c,
	0x81, 0x49, 0x29, 0x59, 0x70, 0xc9, 0xb8, 0x40, 0x65, 0x13, 0x93, 0x72, 0x52, 0x83, 0x53, 0x8b,
	0xca, 0x32, 0x93, 0x53, 0xe1, 0xf2, 0x42, 0x12, 0x5c, 0xec, 0x8e, 0x29, 0x29, 0x45, 0xa9, 0xc5,
	0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x13, 0x77, 0x14, 0x27, 0xdc, 0x86,
	0x24, 0x36, 0xb0, 0xc1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x0e, 0x33, 0x7a, 0x7d,
	0x00, 0x00, 0x00,
}
